baseURL = "https://hexandcube.eu.org"
languageCode = "en-us"
title = "Hexandcube Network"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
paginate = 3

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  google_analytics_id = ""
  twitter_handle = "@hexandcubenetwork"
  showAuthorOnHomepage = false
  showAuthorOnPosts = true
  showPostsOnHomepage = false
  addFrame = true
  addDot = true
